### ISSUE TITLE
Encrypted Password is not supplied decrypted.

### ISSUE THREAD

**Issue by kaojo** [maven-download-plugin/maven-download-plugin#121]
Hi,

If I try to download an archive via the plugin I get an authorization error. With -X I see that the first download attempt results in "Status code: 401, ReasonPhrase:Unauthorized." and the retry gets the error "Status code: 403, ReasonPhrase:Forbidden.". It says the the credentials are being supplied but apparently the password is not decrypted. If I use my password without encryption everything works fine.

My config:
In the pom.xml
```
			<plugin>
				<groupId>com.googlecode.maven-download-plugin</groupId>
				<artifactId>download-maven-plugin</artifactId>
				<version>1.4.0</version>
				<executions>
					<execution>
						<id>download</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>wget</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<url>https://url.to.artifactory.server/file/path/file.tgz</url>
					<unpack>true</unpack>
					<outputDirectory>${project.build.directory}/classes/static/assets</outputDirectory>
					<serverId>artifactory</serverId>
				</configuration>
			</plugin>
```
In settings.xml
```
  <mirrors>
    <mirror>
      <id>artifactory</id>
      <mirrorOf>*</mirrorOf>
      <url>http://url.to.artifactory.server/artifactory/repo</url>
      <name>artifactory</name>
    </mirror>
  </mirrors>

  <servers>
    <server>
      <id>artifactory</id>
      <username>foo</username>
      <password>{encyrptedpw}</password>
    </server>
  </servers>
```

**Comment by brabenetz** [comment]
Have the same problem.
My workaround for now: I change my password to plaintext and then back to the encrypted version.
The artifact will be cached into ~/.m2/repository/.cache/download-maven-plugin/...
It works, until the artifact doesn't change.

**Comment by longtimeago** [comment]
@kaojo Could you, please, try the latest version (1.6.0)?

I've just setup test artifactory server locally (in Docker container), with user `art` and password `XXXX`
Then configured maven-download-plugin 
```xml
<executions>
	<execution>
		<phase>generate-resources</phase>
		<goals>
			<goal>wget</goal>
		</goals>
		<configuration>
			<url>http://172.17.0.2:8082/artifactory/test-repo/</url>
			<serverId>artifactory</serverId>
		</configuration>
	</execution>
</executions>
```

And settings.xml
```xml
        <server>
            <id>artifactory</id>
            <username>art</username>
            <password>{encrypted XXXX}</password>
        </server>
```

With that setup the plugin downloaded repo index successfully

**Comment by kaojo** [comment]
Hi,
Thanks for fixing the issue !
Unfortunately we are not using the plugin anymore. Our setup changed....
Maybe @brabenetz is able to test the new version.

**Comment by longtimeago** [comment]
let's assume it is fixed

**Comment by akomakom** [comment]
Still seeing this issue with `1.9.0`

Plaintext password works (eg `abc`).
Encrypted password does not work (eg output of `mvn --encrypt-password abc`)

Unless of course the example above actually meant a literal word `encrypted` in the password field, I haven't tried that.
